config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :books do
    resources :orders, only: [:create]
  end
  resources :orders, only: [:show]
  get '/profile', to: 'pages#profile'
  get '/bought_books', to: 'pages#bought_books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, :author, :price, presence: true
  validates :description, length: { maximum: 200 }

  has_one_attached :photo
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :date, :user, :book, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end

  # Pundit: white-list approach.

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    # @books = Book.all
    @books = policy_scope(Book)
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user

    # authorize creation before saving it
    if @book.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to profile_path, notice: 'Book has been successfully deleted.'
  end

  private

  def set_book
    @book = Book.find(params[:id])
    # pundit authorization for model
    authorize @book
  end

  def book_params
    params.require(:book).permit(:title, :author, :description, :price, :photo)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    authorize @order
  end

  def create

    @order = Order.new
    @book = Book.find(params[:book_id])
    @order.book = @book
    @order.user = current_user
    @order.date = Time.now

    authorize @order

    if @order.save
      redirect_to order_path(@order)
    else
      redirect_to book_path(@book)
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @books = Book.all.last(6)
    @books_rand = Book.all.sample(3)
  end

  def profile
    @user = current_user
    @books = current_user.books
  end

  def bought_books
    @user = current_user
    @orders = Order.all
    @new_array = @orders.select do |order|
      order.user == current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<div class="container my-5">
  <div class="row">

    <div class="col d-flex justify-content-center">
      <% if @book.photo.attached? %>
        <%= cl_image_tag @book.photo.key, height: 300, width: 400%>
      <% else %>
        <%= cl_image_tag "https://res.cloudinary.com/e-girardi/image/upload/v1629916606/Book_covers/blank_book_jrgpwl.jpg", height: 300, width: 400%>
      <% end  %>
    </div>

    <div class="col">
      <div class="formbg-outer">
        <h1 class="text-center mb-3">Edit your book</h1>
        <div class="formbg">
          <div class="formbg-inner padding-horizontal--48">

            <%= simple_form_for [ @book ], id: "stripe-login" do |f| %>
              <div class="field padding-bottom--12">
                <%= f.input :title %>
                <%= f.input :author %>
                <%= f.input :description %>
                <%= f.input :price %>
                <%= f.input :photo, as: :file %>
              </div>
              <div class="buttons-containter d-flex justify-content-around mt-5">
                <%= f.submit "Update book", class: "btn" %>

                <% if policy(@book).destroy? %>
                  <%= link_to "Delete book", book_path(@book), method: :delete,
                    data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--========== Footer ==========-->
<%= render 'shared/footer' %>

app/views/books/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1544716278-e513176f20b5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80);">
  <div class="banner-container">
    <h1 class="mb-5">Check out these amazing books</h1>
    <h3>We have the perfect story for every moment</h2>
  </div>
</div>

<div class="container">
  <div class="cards">
    <% @books.each do |book| %>
        <div class="accessory__content">
          <% if book.photo.attached? %>
            <%= cl_image_tag book.photo.key, class: "accessory__img"%>
          <% else %>
            <%= cl_image_tag "https://res.cloudinary.com/e-girardi/image/upload/v1629916606/Book_covers/blank_book_jrgpwl.jpg", class: "accessory__img"%>
          <% end  %>
          <h3 class="accessory__title"><%= book.title %></h3>
          <span class="accessory__category"><%= book.author %></span>
           <span class="accessory__preci">R$<%= book.price %></span>
            <%= link_to book_path(book), class:"button accessory__button" do %>
              <i class='bx bx-cart-alt' style='color:#ffffff' ></i>
            <% end %>
         </div>
    <% end %>
  </div>
</div>

<!--========== Footer ==========-->
<%= render 'shared/footer' %>

app/views/books/new.html.erb
<div class="container my-5">

  <div class="row">
    <div class="justify-content-center share__img">
      <%= image_tag "slogan2.png"%>
    </div>

    <div class="col">

      <div class="formbg-outer">
        <h1 class="text-center mb-3">Sell your book</h1>
        <div class="formbg">
          <div class="formbg-inner padding-horizontal--48">
            <%= simple_form_for [ @book ], id: "stripe-login" do |f| %>
              <div class="field padding-bottom--12">
                <%= f.input :title %>
                <%= f.input :author %>
                <%= f.input :description, as: :text %>
                <%= f.input :price %>
                <%= f.input :photo, as: :file %>
              </div>

              <div class="buttons-containter d-flex justify-content-around mt-5">
                <%= f.submit "Sell this book", class: "btn btn-alert" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/books/show.html.erb
<div class="container my-5">
  <div class="row d-flex align-items-center">

    <div class="col d-flex justify-content-center">
      <% if @book.photo.attached? %>
        <%= cl_image_tag @book.photo.key, height: 300, width: 400%>
      <% else %>
        <%= cl_image_tag "https://res.cloudinary.com/e-girardi/image/upload/v1629916606/Book_covers/blank_book_jrgpwl.jpg", height: 300, width: 400%>
      <% end  %>
    </div>

    <div class="col d-flex justify-content-center">
      <div class="formbg-outer">
        <div class="formbg">
          <div class="formbg-inner padding-horizontal--48">
            <div class="info text-right">
              <h1 class="pb-20 my-2"><%= @book.title %></h1>
              <p class="mb-5"><em>Being sold by </em><strong><%="#{@book.user.first_name}"%></strong></p>
              <p class="pb-20 my-3">"<%= @book.description %>"</p>
              <%# <i class="fas fa-truck"></i> %>
              <div class="order-ad">
                <h4>Order it now and receive it in up to 3 days!</h4>
              </div>
              <h3 class="mb-3">R$<%= @book.price %></h3>
              <div class="container d-flex justify-content-center mt-5 w-70%">
                <%= link_to "Buy this Book", book_orders_path(@book), method: :post, class: "button pt-80 "  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--========== Footer ==========-->
<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container my-5">
  <div class="row d-flex align-items-center">

    <div class="col d-flex justify-content-center">
      <% if @order.book.photo.attached? %>
        <%= cl_image_tag @order.book.photo.key, height: 300, width: 400%>
      <% else %>
        <%= cl_image_tag "https://res.cloudinary.com/e-girardi/image/upload/v1629916606/Book_covers/blank_book_jrgpwl.jpg", height: 300, width: 400%>
      <% end  %>
    </div>

    <div class="col">
      <div class="formbg-outer">
        <div class="formbg">
          <div class="formbg-inner padding-horizontal--48">
            <div class="info text-center">
              <h1>Your purchase was successfully completed!</h1> <br>
              <h3><strong><%="#{@order.user.first_name}"%></strong>
                is already preparing your order
                and you should receive it soon.</h3><br>
              <h5>Click on the button below to check the details of your purchase</h5>
              <div class="container d-flex justify-content-center mt-5 w-70%">
                <%= link_to "My orders", bought_books_path, class: "button pt-80 "  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/bought_books.html.erb
<div class="table-container mx-5">
    <div class="col-10 mx-5">
      <h1 class="my-4"><%="Hello, #{@user.first_name}. " %></h1>
      <h3 class="my-4">Check out the books you've bought</h3>

      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Price</th>
            <th scope="col">Seller</th>
            <th scope="col">Date</th>
          </tr>
        </thead>

        <% @new_array.each do |order| %>
          <tbody>
            <tr>
              <td><%= order.book.title %></td>
              <td><%= order.book.author %></td>
              <td><%= "R$#{order.book.price}" %></td>
              <td><%= order.book.user.first_name %></td>
              <td><%= order.date%></td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= link_to 'Go back', root_path, class:'button mt-3' %>
    </div>
</div>
<!--========== Footer ==========-->
<%= render 'shared/footer' %>

app/views/pages/home.html.erb
<!--========== Discover ==========-->
<section class="home" id="home">
    <div class="home__container bd-container bd-grid">
        <div class="home__img">
          <%= image_tag "Book-home.png"  %>
        </div>

        <div class="home__data">
            <h1 class="home__title">Book Story</h1>
            <p class="home__description">Find the perfect story for you</p>
            <%= link_to "Discover", books_path, class: "button" %>
        </div>
    </div>
</section>

<!--========== Sell ==========-->
<section class="share section bd-container" id="share">
    <div class="share__container bd-grid">
        <div class="share__data">
            <h2 class="section-title-center">Sell a book</h2>
            <p class="share__description">Share your most exciting stories with others</p>
            <%= link_to "Sell", new_book_path, class: "button p-100" %>
        </div>

        <div class="share__img">
          <%= image_tag "share-book.png" %>
        </div>
    </div>
</section>

<!--========== Our Suggestions ==========-->
<section class="decoration section bd-container" id="decoration">
    <h2 class="section-title">Our Suggestions</h2>
    <div class="decoration__container bd-grid">
        <% @books_rand.each do |book| %>
            <div class="decoration__data text-center d-flex flex-column">
                <div>
                  <% if book.photo.attached? %>
                    <%= cl_image_tag book.photo.key, class: "accessory__img"%>
                  <% else %>
                    <%= cl_image_tag "https://res.cloudinary.com/e-girardi/image/upload/v1629916606/Book_covers/blank_book_jrgpwl.jpg", class: "accessory__img"%>
                  <% end  %>
                    <h3 class="decoration__title"><%= book.title %></h3>
                </div>
                <div class ="mt-auto">
                    <%= link_to "Go Shopping", book_path(book), class: "button button-link button-suggestion" %>
                </div>
            </div>
        <% end %>
    </div>
</section>

<!--========== New Books ==========-->
<section class="accessory section bd-container" id="accessory">
    <h2 class="section-title">New Books</h2>
    <div class="accessory__container bd-grid">
        <% @books.each do |book| %>

            <div class="accessory__content">
              <% if book.photo.attached? %>
                <%= cl_image_tag book.photo.key, class: "accessory__img"%>
              <% else %>
                <%= cl_image_tag "https://res.cloudinary.com/e-girardi/image/upload/v1629916606/Book_covers/blank_book_jrgpwl.jpg", class: "accessory__img"%>
              <% end  %>
                <h3 class="accessory__title"><%= book.title %></h3>
                <span class="accessory__category"><%= book.author %></span>
                <span class="accessory__preci"><%= book.price %></span>
                <%= link_to book_path(book), class:"button accessory__button" do %>
                    <i class='bx bx-cart-alt' style='color:#ffffff' ></i>
                <% end %>
            </div>
        <% end %>
    </div>
</section>

<!--========== Footer ==========-->
<%= render 'shared/footer' %>

app/views/pages/profile.html.erb
<div class="table-container mx-5">
    <div class="col-10 mx-5">
      <h1 class="my-4"><%="Hello, #{@user.first_name}. " %></h1>
      <h3 class="my-4">Check out your books</h3>

      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Price</th>
          </tr>
        </thead>

        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to "#{book.title}", edit_book_path(book) %></td>
              <td><%= book.author %></td>
              <td><%= "R$#{book.price}" %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= link_to 'Go back', root_path, class:'button mt-3' %>
    </div>

</div>
<!--========== Footer ==========-->
<%= render 'shared/footer' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer section">
    <div class="footer__container">
        <div class="footer__content">
            <h3 class="footer__title">Our Services</h3>
            <ul>
                <li><a href="#" class="footer__link">Sell </a></li>
                <li><a href="#" class="footer__link">Buy</a></li>
            </ul>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Our Company</h3>
            <ul>
                <li><a href="#" class="footer__link">About us</a></li>
                <li><a href="#" class="footer__link">Our mission</a></li>
            </ul>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Social</h3>
            <a href="#" class="footer__social"><i class='bx bxl-facebook-circle' style='color:#ffffff' ></i></a>
            <a href="#" class="footer__social"><i class='bx bxl-twitter' style='color:#ffffff' ></i></a>
            <a href="#" class="footer__social"><i class='bx bxl-instagram-alt' style='color:#ffffff' ></i></a>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>

    <%= image_tag "Logo4.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Store", books_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My books", profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My orders", bought_books_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sell a book", new_book_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://thispersondoesnotexist.com/image", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login / Sign Up", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>